version: '3'
services:
  api:
    build: ./todo-api
    ports:
      - "8000:8000"
    command: go test
    
  client:
    build: ./todo-client
    ports: 
      - "4200:80"

  tests:
    build:
      context: .
      dockerfile: ./todo-api/Dockerfile.test
